### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by goloroden** [squaremo/bitsyntax-js#9]
@squaremo I'm sorry, I first posted this as a comment to the already closed issue #6.

Hence, here we go, once again:

Could you please release a new version `0.0.5` of this library which contains the license commit? Currently, `0.0.4` is the latest one, but this does not include the license information in its `package.json` file, and hence our license checker fails :-(

**Comment by anoff** [comment]
bumping for feedback. Can 0.0.4 be considered MIT licensed?

**Comment by hpurmann** [comment]
Bumping again. Our license checker fails as well ... 🤕

**Comment by squaremo** [comment]
Thanks for reminding me 👍
